const cx=window.ClipsX,c=cx.context,source=c.representation.text||'',app=document.querySelector('#app');document.documentElement.dataset.theme=c.theme
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))
const utf8Bytes=value=>new TextEncoder().encode(value)
const encode=value=>{const bytes=utf8Bytes(value);let binary='';for(let index=0;index<bytes.length;index+=0x8000)binary+=String.fromCharCode(...bytes.subarray(index,index+0x8000));return btoa(binary)}
const strictBytes=value=>{const compact=value.replace(/\s/g,'');if(!compact||compact.length%4!==0||!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(compact))throw Error('This text is not valid Base64.');const raw=atob(compact);return Uint8Array.from(raw,ch=>ch.charCodeAt(0))}
const hex=bytes=>[...bytes.slice(0,4096)].map((value,index)=>`${index&&index%16===0?'\n':''}${value.toString(16).padStart(2,'0')}`).join(' ')
const decoded=()=>{const bytes=strictBytes(source);try{return{value:new TextDecoder('utf-8',{fatal:true}).decode(bytes),bytes,binary:false}}catch{return{value:hex(bytes),bytes,binary:true}}}
let valid=false,decodedValue=null;try{decodedValue=decoded();valid=true}catch{}let mode=valid?'decode':'encode',copied=''
const result=()=>mode==='encode'?{value:encode(source),bytes:utf8Bytes(source),binary:false}:decodedValue
const copy=(key,value,mime='text/plain')=>{cx.submitText(mime,value,'copy');copied=key;render();setTimeout(()=>{if(copied===key){copied='';render()}},1400)}
function render(){const output=result(),invalid=mode==='decode'&&!output;const inputLabel=mode==='encode'?'Plain text':'Base64',outputLabel=mode==='encode'?'Base64':'Decoded',inputBytes=mode==='encode'?utf8Bytes(source).length:valid?decodedValue.bytes.length:0;app.innerHTML=`<section class="shell"><header class="top"><div class="identity"><span class="mark">64</span><div><h1>Base64 Codec</h1><p>Everything stays on this device</p></div></div><div class="switch" role="tablist" aria-label="Codec direction"><button role="tab" data-mode="encode" aria-selected="${mode==='encode'}">Encode</button><button role="tab" data-mode="decode" aria-selected="${mode==='decode'}">Decode</button></div></header><div class="flow"><article class="card"><div class="card-head"><span><b>${inputLabel}</b><small>${source.length.toLocaleString()} chars</small></span><button class="copy" data-copy="input">${copied==='input'?'Copied':'Copy'}</button></div><pre>${esc(source||'Empty text')}</pre></article><div class="direction" aria-hidden="true"><span>→</span><small>${mode==='encode'?'UTF-8 → 64':'64 → bytes'}</small></div><article class="card result ${invalid?'invalid':''}"><div class="card-head"><span><b>${outputLabel}</b><small>${invalid?'Unavailable':`${(output?.bytes.length??0).toLocaleString()} bytes${output?.binary?' · binary':''}`}</small></span>${!invalid&&!output?.binary?`<button class="copy" data-copy="result">${copied==='result'?'Copied':'Copy'}</button>`:''}</div><pre>${esc(invalid?'Enter valid padded Base64 to decode.':output?.value||'Empty result')}</pre></article></div>${output?.binary?'<div class="binary-note"><span>Binary output</span><p>Showing the first 4 KiB as hexadecimal. Text copying is unavailable because decoding would lose the original bytes.</p></div>':''}<footer><span>${inputBytes.toLocaleString()} input bytes</span><span>Local · offline</span></footer></section>`;app.querySelectorAll('[data-mode]').forEach(button=>button.onclick=()=>{mode=button.dataset.mode;render()});app.querySelector('[data-copy=input]')?.addEventListener('click',()=>copy('input',source));app.querySelector('[data-copy=result]')?.addEventListener('click',()=>copy('result',output.value))}
render();cx.ready()
